### ISSUE TITLE
cleaning up data releases

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#127]
There are two different data release types that need to be cleanly organized.   
These need to be released into an appropriate location.

- [ ] - Controlled access data sets
          SraRunTable.noCram.noExome.noWGS.totalRNA.txt
- [ ] - All other data sets
         1.  https://github.com/adeslatt/sbas_gtf/releases/tag/rMATS.3.2.5.gencode.v30
                 a. https://github.com/adeslatt/sbas_gtf/files/4604418/fromGTF.SE.txt
                 b. https://github.com/adeslatt/sbas_gtf/files/4604418/fromGTF.RI.txt
         2.  https://github.com/adeslatt/sbas_test/releases/tag/rMATS.3.2.5.GTEx.V8.final_matrices         
                 a. https://github.com/adeslatt/sbas_test/releases/download/rMATS.3.2.5.GTEx.V8.final_matrices/rmats_final.se.jc.ijc.txt.gz
                 b. https://github.com/adeslatt/sbas_test/releases/download/rMATS.3.2.5.GTEx.V8.final_matrices/rmats_final.se.jc.sjc.txt.gz

**Comment by pnrobinson** [comment]
stale issue, closing
