### ISSUE TITLE
https://github.com/lifebit-ai/rmats-nf run once with reporting, timing, etc on

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#140]
To elevate the submission of this paper, the nextflow pipeline https://github.com/lifebit-ai/rmats-nf should be run once with all the reporting features on so that:
- [ ] flow diagram generated and added to the github repository readme
- [ ] reports showing timing (for the example run) could be made
- [ ] if available all the quality reports made available from the run

Any other features to highlight the utility of this in this effort

**Comment by pnrobinson** [comment]
@adeslatt @cgpu  This is not high priority, but if we want to do this it is now or never. I do not think this is absolutely required so feel free to close!

**Comment by adeslatt** [comment]
per @pnrobinson closing
