### ISSUE TITLE
figure 3 reconcile

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#145]
@cgpu will reconcile figure 3 updates -- with an eye towards paying attention to phenotype annotation -- @cgpu remember to rely upon the pData(obj) that we made.  

the Bayesian analysis here -- may be limited to skipping (SE) alternative splicing events alone.

*tissues will be limited to only to those tissues that have significant events > 50 -- for downstream analysis.*

**Comment by pnrobinson** [comment]
stale, closing
