### ISSUE TITLE
make a new figure

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#159]
Using figure1d.pdf 

- [x] - numberOfSexedBiasedSplicingEvents.pdf (former figure 1d.pdf)

Make a figure showing the number of sex-biased events based upon gene expression
(comparable to the number of sex-biased events based upon alternative splicing events)

Also then a figure based upon the number of sex-biased events based upon junction (ijc) expression)

Also then a figure based upon the number of sex-biased events based upon junction (sjc) expression)

- [ ] - numberOfSexBiasedGeneExpressionEventsByTissue.pdf

- [ ] - numberOfSexBiasedIJCExpressionEventsByTIssue.pdf

- [ ] - numberOfSexBiasedSJCExpressionEventsByTissue.pdf

**Comment by pnrobinson** [comment]
stale issue
