### ISSUE TITLE
clean up the 3 create scripts to produce only the named pdf in the script

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#180]
A very rough cut was made and now three notebooks exist that have the names as indicated.
please trim down each of them to reflect the name of each of the files.

- [ ]  create_AS_events_per_gene_figure.ipynb
```r
ggsave("../pdf/AS_events_per_gene.pdf",g, height = 4.5, width = 4)
```
- [ ] create_SplicingIndex_figure.ipynb
```r
ggsave("../pdf/splicingIndex.pdf",g2, height = 4.5, width = 4)
```
- [ ] create_tissue_piechart_figure.ipynb
```r
pdf("../pdf/tissue-piechart.pdf")
```

Clean and trim the files to its only needed components

**Comment by pnrobinson** [comment]
stale issue, closing.
