### ISSUE TITLE
Create union of genesets and universes per tissue across AS splice types

### ISSUE THREAD

**Issue by cgpu** [TheJacksonLaboratory/sbas#198]
39 analyses in the end, 1 per tissue instead of 5 * 39 = 195 analyses.

Nifty unix command to be used courtesy of @pnrobinson 

```bash
ls *.* | grep skin_sun_exposed | grep universe | grep sex_as_events | xargs cat | sort | uniq
```

This is to be added in the `sbas-nf` pipeline before running ontologizer and resume this completed analysis: 

https://cloudos.lifebit.ai/app/jobs/5ef3627e143fa00113289c23

**Comment by pnrobinson** [comment]
this has been implemented.
