### ISSUE TITLE
Ways of assessing the Stan model

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#206]
[fitting bayesian models with stan and R](https://www.weirdfishes.blog/blog/fitting-bayesian-models-with-stan-and-r/) 

[running diagnostics](https://www.weirdfishes.blog/blog/fitting-bayesian-models-with-stan-and-r/#run-diagnostics)

**Comment by cgpu** [comment]
Here's the Rmd that generates this btw https://github.com/DanOvando/weird-fishes/blob/master/content/blog/2018-02-16-a-practical-introduction-to-stan.Rmd

**Comment by cgpu** [comment]
Comment from Andrew Gelman on this:
https://discourse.mc-stan.org/t/aic-bic/11036/5
(He doesn't appreciate BIC, AIC is more ok-ish but in general he is not fond of them for assessing bayesian models)
![image](https://user-images.githubusercontent.com/38183826/88068151-bbbcbd00-cb67-11ea-8a4e-073280bbaf4f.png)

**Comment by pnrobinson** [comment]
I am going to close this since it is no longer relevant for the current publication
