### ISSUE TITLE
Heatmap fix - These files include all the events before screening

### ISSUE THREAD

**Issue by karleg** [TheJacksonLaboratory/sbas#208]
https://github.com/TheJacksonLaboratory/sbas/blob/26da59e86af55664784672e640947f8bc4bc8a35/Rmd/expressionHeatplot.Rmd#L60

This is different than the description in the manuscript:

"The log-fold-changes obtained from voom's dierential expression analysis were obtained for each tissue, where genes that were screened out from the DE analysis of a tissue were assigned a log-fold-change of 0. Genes with a logFC of 0 in all tissues were removed"

**Comment by pnrobinson** [comment]
@karleg  is this issue closeable?

**Comment by karleg** [comment]
yes, I just pushed pushed the local version of the corrected notebook, which should be identical to the one that I pushed after opening the issue
