### ISSUE TITLE
dge-go expects ontologizer output

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#229]
This file has hard coded paths - easy to change - except it expects output from an unknown file. @pnrobinson  or @cgpu can you offer an assist?

**Comment by pnrobinson** [comment]
I would suggest let's not do the GO stuff on the platform. We did not actually use this script and we need to repeat it anyway. We can describe how to do things in the README somewhere.

**Comment by pnrobinson** [comment]
I did this locally
