### ISSUE TITLE
eventBoxPlot has a syntax error "rmats_id=)"

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#230]
rmats_id is the first column of the file being read - I am not familiar enough with python to find this quickly -- I ran this as a python file after running `jupytext --to py eventBoxPlot.ipynb".  Error occurs straight away. @cgpu can you offer an assist?

**Comment by pnrobinson** [comment]
@adeslatt I was working on this but did not finish -- and in the meantime we found another way to do it. Let's just delete this!
