### ISSUE TITLE
delete the following notebooks

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/sbas#231]
Hi @pnrobinson, @cgpu,

I think we should:
- [x] delete getPhenoData.ipynb
- [x] delete keep_intersect.ipynb
- [x] delete eventBoxPlot.ipynb (only one that may be questionable -- but it has a bug - @cgpu looking at it

@pnrobinson I think you asked this before.

**Comment by pnrobinson** [comment]
Agree, let's delete
-  getPhenoData.ipynb
- keep_intersect.ipynb
I started to write ``eventBoxPlot.ipynb`` to get values from individual samples but I never finished and we can delete it with or without bug; I think that we figured out how to get these values in R?

**Comment by cgpu** [comment]
Ok taking this on! Deleting now and submitting tiny PR @pnrobinson @adeslatt
