### ISSUE TITLE
Add documentation on separating dependencies scripts Vs analysis scripts [LOGIC]

### ISSUE THREAD

**Issue by cgpu** [TheJacksonLaboratory/sbas#86]
## Separate the logic of dependencies scripts Vs analysis scripts

As a rule of thumb any 🆕 dependency should be added in a separate **dependencies script** used for configuring our environment.

We make use of two types of such files:

1. `requirements.txt`, a one column file which has one package in each line.
The naming convention should be 

`channel::package=version`.

they look like this:

2. `install.R`

The priority of the method that we use to install dependencies is the above.
First we try with `conda install` - we do this via the `requirements.txt` file, which serves both as our package metadata file and active installation instructions file.

If that for some reason is not possible, we move the `install.packages()` or `devtools::install_github()` command in the file named `install.R` to be able to install programmatically the dependencies.

For a reminder of the method refer to the [dependencies/README.md](https://github.com/TheJacksonLaboratory/sbas/tree/master/dependencies#update-the-base-conda-environment)

![image](https://user-images.githubusercontent.com/38183826/75594750-b5775880-5a81-11ea-9f47-66592b6aac65.png)

As the different figures will have different dependencies, let's try to organise dependencies in subfolders named after the figure sections.

The dependencies folder structure therefore should take the structure:

```console

➜ tree dependencies
dependencies
├── figure1
│   ├── README.md
│   ├── install.R
│   └── requirements.txt
├── figure2
│   ├── README.md
│   ├── install.R
│   └── requirements.txt
.
.
.
└── figure5
    ├── README.md
    ├── install.R
    └── requirements.txt

5 directories, 15 files
```

I will add a section for this in the `README.md` as we haven't all discussed this together.

_Originally posted by @cgpu in https://github.com/TheJacksonLaboratory/sbas/issues/81#issuecomment-592780486_

**Comment by pnrobinson** [comment]
stale, I think we can close this.
